### ISSUE TITLE
关于 lidar_end 的疑问

### ISSUE THREAD

**Issue by SharkPeppero** [liangheming/M_FASTLIVO#1]
作者你好，
关于数据同步处理那一块，我看代码的意思是，如果雷达帧同步到了imu数据但是没有同步到图像数据，lidar_end设为true，
但实际数据集的包内 image与lidar 的时间戳是一一对应的，按照理论来说不应该 每一次同步lidar都可以同步到image，lidar_end标志位应该始终为false把
我测试的情况发现 这个标志位大概是间隔的 true或false ，这样设计的目的是为什么

**Comment by liangheming** [comment]
lidar_end表示当前同步的带有imu的数据包以lidar数据结尾，fatlivo1中一共就两种类型的同步包，一个以lidar数据结尾，一个以图像结尾，原因是需要用这两种数据进行观测更新。以lidar数据结尾的数据包还有一个作用就是需要对lidar帧进行畸变矫正。当然官方提供的数据包lidar和image都是10帧，会有一定的误导。实际上两个传感器一般不同帧

**Comment by SharkPeppero** [comment]
了解~
